#!/bin/bash
./collect_opt.sh

cd ../collection
./build.sh
START=$(date +%s.%N)
./optimize.sh push brood_lord 1 > brood_lord1p &
OPTPID="$!"
sleep 1
echo "pushing 1 void_ray. Time to beat: 10min aka 600s\n"
tail -f ga_analytics.log &
wait $OPTPID || {echo "error"}
END=$(date +%s.%N)
DIFF=$(echo "$END - $START" | bc)
echo "total running time:"
echo $DIFF
