#!/bin/bash
./collect_opt.sh

cd ../collection
./build.sh
START=$(date +%s.%N)
./optimize.sh push void_ray 1 > void_ray1p &
OPTPID="$!"
sleep 1
echo "pushing 1 void_ray. Time to beat: 5:30min aka 330s\n"
tail -f ga_analytics.log &
wait $OPTPID || {echo "error"}
END=$(date +%s.%N)
DIFF=$(echo "$END - $START" | bc)
echo "total running time:"
echo $DIFF
